In [18]:
import os
from pathlib import Path

import pandas as pd
import numpy as np

In [19]:
DATASET_PATH = Path("../data/raw/archive")

In [20]:
csv_files = sorted(DATASET_PATH.rglob("*.csv"))

print(f"Total CSV files: {len(csv_files)}")

for file in csv_files:
    print(file)

Total CSV files: 18
..\data\raw\archive\01-12\DrDoS_DNS.csv
..\data\raw\archive\01-12\DrDoS_LDAP.csv
..\data\raw\archive\01-12\DrDoS_MSSQL.csv
..\data\raw\archive\01-12\DrDoS_NetBIOS.csv
..\data\raw\archive\01-12\DrDoS_NTP.csv
..\data\raw\archive\01-12\DrDoS_SNMP.csv
..\data\raw\archive\01-12\DrDoS_SSDP.csv
..\data\raw\archive\01-12\DrDoS_UDP.csv
..\data\raw\archive\01-12\Syn.csv
..\data\raw\archive\01-12\TFTP.csv
..\data\raw\archive\01-12\UDPLag.csv
..\data\raw\archive\03-11\LDAP.csv
..\data\raw\archive\03-11\MSSQL.csv
..\data\raw\archive\03-11\NetBIOS.csv
..\data\raw\archive\03-11\Portmap.csv
..\data\raw\archive\03-11\Syn.csv
..\data\raw\archive\03-11\UDP.csv
..\data\raw\archive\03-11\UDPLag.csv

In [21]:
sample = pd.read_csv(
    csv_files[0],
    low_memory=False
)

In [22]:
sample.head()

,Unnamed: 0,Flow ID,Source IP,Source Port,Destination IP,Destination Port,Protocol,Timestamp,Flow Duration,Total Fwd Packets,...,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,SimillarHTTP,Inbound,Label
0,425,172.16.0.5-192.168.50.1-634-60495-17,172.16.0.5,634,192.168.50.1,60495,17,2018-12-01 10:51:39.813448,28415,97,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
1,430,172.16.0.5-192.168.50.1-60495-634-17,192.168.50.1,634,172.16.0.5,60495,17,2018-12-01 10:51:39.820842,2,2,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,DrDoS_DNS
2,1654,172.16.0.5-192.168.50.1-634-46391-17,172.16.0.5,634,192.168.50.1,46391,17,2018-12-01 10:51:39.852499,48549,200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
3,2927,172.16.0.5-192.168.50.1-634-11894-17,172.16.0.5,634,192.168.50.1,11894,17,2018-12-01 10:51:39.890213,48337,200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS
4,694,172.16.0.5-192.168.50.1-634-27878-17,172.16.0.5,634,192.168.50.1,27878,17,2018-12-01 10:51:39.941151,32026,200,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,DrDoS_DNS

In [23]:
sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 5074413 entries, 0 to 5074412
Data columns (total 88 columns):
 #   Column                        Dtype
---  ------                        -----
 0   Unnamed: 0                    int64
 1   Flow ID                       str
 2    Source IP                    str
 3    Source Port                  int64
 4    Destination IP               str
 5    Destination Port             int64
 6    Protocol                     int64
 7    Timestamp                    str
 8    Flow Duration                int64
 9    Total Fwd Packets            int64
 10   Total Backward Packets       int64
 11  Total Length of Fwd Packets   float64
 12   Total Length of Bwd Packets  float64
 13   Fwd Packet Length Max        float64
 14   Fwd Packet Length Min        float64
 15   Fwd Packet Length Mean       float64
 16   Fwd Packet Length Std        float64
 17  Bwd Packet Length Max         float64
 18   Bwd Packet Length Min        float64
 19   Bwd Packet Length Mean       float64
 20   Bwd Packet Length Std        float64
 21  Flow Bytes/s                  float64
 22   Flow Packets/s               float64
 23   Flow IAT Mean                float64
 24   Flow IAT Std                 float64
 25   Flow IAT Max                 float64
 26   Flow IAT Min                 float64
 27  Fwd IAT Total                 float64
 28   Fwd IAT Mean                 float64
 29   Fwd IAT Std                  float64
 30   Fwd IAT Max                  float64
 31   Fwd IAT Min                  float64
 32  Bwd IAT Total                 float64
 33   Bwd IAT Mean                 float64
 34   Bwd IAT Std                  float64
 35   Bwd IAT Max                  float64
 36   Bwd IAT Min                  float64
 37  Fwd PSH Flags                 int64
 38   Bwd PSH Flags                int64
 39   Fwd URG Flags                int64
 40   Bwd URG Flags                int64
 41   Fwd Header Length            int64
 42   Bwd Header Length            int64
 43  Fwd Packets/s                 float64
 44   Bwd Packets/s                float64
 45   Min Packet Length            float64
 46   Max Packet Length            float64
 47   Packet Length Mean           float64
 48   Packet Length Std            float64
 49   Packet Length Variance       float64
 50  FIN Flag Count                int64
 51   SYN Flag Count               int64
 52   RST Flag Count               int64
 53   PSH Flag Count               int64
 54   ACK Flag Count               int64
 55   URG Flag Count               int64
 56   CWE Flag Count               int64
 57   ECE Flag Count               int64
 58   Down/Up Ratio                float64
 59   Average Packet Size          float64
 60   Avg Fwd Segment Size         float64
 61   Avg Bwd Segment Size         float64
 62   Fwd Header Length.1          int64
 63  Fwd Avg Bytes/Bulk            int64
 64   Fwd Avg Packets/Bulk         int64
 65   Fwd Avg Bulk Rate            int64
 66   Bwd Avg Bytes/Bulk           int64
 67   Bwd Avg Packets/Bulk         int64
 68  Bwd Avg Bulk Rate             int64
 69  Subflow Fwd Packets           int64
 70   Subflow Fwd Bytes            int64
 71   Subflow Bwd Packets          int64
 72   Subflow Bwd Bytes            int64
 73  Init_Win_bytes_forward        int64
 74   Init_Win_bytes_backward      int64
 75   act_data_pkt_fwd             int64
 76   min_seg_size_forward         int64
 77  Active Mean                   float64
 78   Active Std                   float64
 79   Active Max                   float64
 80   Active Min                   float64
 81  Idle Mean                     float64
 82   Idle Std                     float64
 83   Idle Max                     float64
 84   Idle Min                     float64
 85  SimillarHTTP                  str
 86   Inbound                      int64
 87   Label                        str
dtypes: float64(45), int64(37), str(6)
memory usage: 3.3 GB

In [24]:
sample.shape

(5074413, 88)

In [25]:
sample.describe()

c:\Machine_Learning-Capstone\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Machine_Learning-Capstone\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,Unnamed: 0,Source Port,Destination Port,Protocol,Flow Duration,Total Fwd Packets,Total Backward Packets,Total Length of Fwd Packets,Total Length of Bwd Packets,Fwd Packet Length Max,...,min_seg_size_forward,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Inbound
count,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,...,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06,5.074413e+06
mean,1.380064e+04,8.000962e+02,3.279212e+04,1.699142e+01,7.176140e+03,6.013596e+00,8.004867e-03,2.952438e+03,6.768139e+00,1.377942e+03,...,-3.680966e+07,6.703219e+01,1.305199e+01,8.437979e+01,5.788418e+01,2.331791e+03,1.054355e+02,2.420004e+03,2.240776e+03,9.990669e-01
std,8.020386e+03,1.851189e+03,1.892478e+04,3.194000e-01,7.711845e+05,5.953501e+02,2.950822e+00,9.122037e+03,6.837585e+03,2.999557e+02,...,1.943476e+08,2.653840e+04,6.162152e+03,2.883959e+04,2.557915e+04,3.318188e+05,4.571781e+04,3.434159e+05,3.242934e+05,3.053264e-02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,-1.408238e+09,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,6.844000e+03,5.810000e+02,1.643000e+04,1.700000e+01,1.000000e+00,2.000000e+00,0.000000e+00,2.928000e+03,0.000000e+00,1.464000e+03,...,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
50%,1.377600e+04,7.270000e+02,3.279400e+04,1.700000e+01,1.000000e+00,2.000000e+00,0.000000e+00,2.944000e+03,0.000000e+00,1.472000e+03,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
75%,2.074100e+04,8.750000e+02,4.918300e+04,1.700000e+01,2.000000e+00,2.000000e+00,0.000000e+00,2.944000e+03,0.000000e+00,1.472000e+03,...,1.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00
max,2.818200e+04,6.550800e+04,6.553500e+04,1.700000e+01,1.200000e+08,1.001480e+05,4.602000e+03,1.526642e+07,1.099376e+07,3.212000e+04,...,1.480000e+03,4.872242e+07,7.827056e+06,4.872242e+07,4.872242e+07,1.017888e+08,6.600292e+07,1.037700e+08,1.017888e+08,1.000000e+00

In [26]:
sample.isnull().sum()

Unnamed: 0         0
Flow ID            0
 Source IP         0
 Source Port       0
 Destination IP    0
                  ..
 Idle Max          0
 Idle Min          0
SimillarHTTP       0
 Inbound           0
 Label             0
Length: 88, dtype: int64

In [27]:
summary = []
for file in csv_files:
    print(f"Reading {file.name}...")
    try:
        df = pd.read_csv(file, nrows=1000, low_memory=False)
        summary.append({
            "File": file.name,
            "Columns": len(df.columns),
            "Column Names": ", ".join(df.columns[:5]) + "...",
            "Missing Values": int(df.isnull().sum().sum())
        })
    except Exception as e:
        print(f"Error reading {file.name}: {e}")

Reading DrDoS_DNS.csv...
Reading DrDoS_LDAP.csv...
Reading DrDoS_MSSQL.csv...
Reading DrDoS_NetBIOS.csv...
Reading DrDoS_NTP.csv...
Reading DrDoS_SNMP.csv...
Reading DrDoS_SSDP.csv...
Reading DrDoS_UDP.csv...
Reading Syn.csv...
Reading TFTP.csv...
Reading UDPLag.csv...
Reading LDAP.csv...
Reading MSSQL.csv...
Reading NetBIOS.csv...
Reading Portmap.csv...
Reading Syn.csv...
Reading UDP.csv...
Reading UDPLag.csv...

In [28]:
def profile_csv(file, chunksize=500_000):
    """Profile one CSV in a single chunked pass: never holds the full file in memory."""
    size_mb = file.stat().st_size / 1024**2

    row_count = 0
    n_columns = None
    missing = 0
    hashes = []

    for chunk in pd.read_csv(file, chunksize=chunksize, low_memory=False):
        if n_columns is None:
            n_columns = chunk.shape[1]
        row_count += len(chunk)
        missing += int(chunk.isnull().sum().sum())
        hashes.append(pd.util.hash_pandas_object(chunk, index=False).values)

    all_hashes = np.concatenate(hashes)
    duplicate_rows = int(len(all_hashes) - len(np.unique(all_hashes)))

    return {
        "File": f"{file.parent.name}/{file.name}",
        "Rows": row_count,
        "Columns": n_columns,
        "Missing Values": missing,
        "Duplicate Rows": duplicate_rows,
        "Size (MB)": round(size_mb, 2),
    }

In [29]:
profile_rows = []

for file in csv_files:
    print(f"Profiling {file.parent.name}/{file.name}...")
    profile_rows.append(profile_csv(file))

Profiling 01-12/DrDoS_DNS.csv...
Profiling 01-12/DrDoS_LDAP.csv...
Profiling 01-12/DrDoS_MSSQL.csv...
Profiling 01-12/DrDoS_NetBIOS.csv...
Profiling 01-12/DrDoS_NTP.csv...
Profiling 01-12/DrDoS_SNMP.csv...
Profiling 01-12/DrDoS_SSDP.csv...
Profiling 01-12/DrDoS_UDP.csv...
Profiling 01-12/Syn.csv...
Profiling 01-12/TFTP.csv...
Profiling 01-12/UDPLag.csv...
Profiling 03-11/LDAP.csv...
Profiling 03-11/MSSQL.csv...
Profiling 03-11/NetBIOS.csv...
Profiling 03-11/Portmap.csv...
Profiling 03-11/Syn.csv...
Profiling 03-11/UDP.csv...
Profiling 03-11/UDPLag.csv...

In [30]:
profile_df = pd.DataFrame(profile_rows)
profile_df

,File,Rows,Columns,Missing Values,Duplicate Rows,Size (MB)
0,01-12/DrDoS_DNS.csv,5074413,88,31,0,2034.48
1,01-12/DrDoS_LDAP.csv,2181542,88,12,0,874.81
2,01-12/DrDoS_MSSQL.csv,4524498,88,14,0,1801.66
3,01-12/DrDoS_NetBIOS.csv,4094986,88,8,0,1618.84
4,01-12/DrDoS_NTP.csv,1217007,88,31,0,615.13
5,01-12/DrDoS_SNMP.csv,5161377,88,12,0,2071.93
6,01-12/DrDoS_SSDP.csv,2611374,88,2,0,1194.65
7,01-12/DrDoS_UDP.csv,3136802,88,8,0,1436.27
8,01-12/Syn.csv,1582681,88,202277,0,607.79
9,01-12/TFTP.csv,20107827,88,10497,0,8871.09
10,01-12/UDPLag.csv,370605,88,36132,0,150.65
11,03-11/LDAP.csv,2113234,88,13,0,831.03
12,03-11/MSSQL.csv,5775786,88,7,0,2275.68
13,03-11/NetBIOS.csv,3455899,88,6,0,1352.76
14,03-11/Portmap.csv,191694,88,1,0,74.97
15,03-11/Syn.csv,4320541,88,94,482799,1790.40
16,03-11/UDP.csv,3782206,88,4,0,1709.74
17,03-11/UDPLag.csv,725165,88,3,0,304.98

In [31]:
profile_df.to_csv("../reports/dataset_summary.csv", index=False)
profile_df

,File,Rows,Columns,Missing Values,Duplicate Rows,Size (MB)
0,01-12/DrDoS_DNS.csv,5074413,88,31,0,2034.48
1,01-12/DrDoS_LDAP.csv,2181542,88,12,0,874.81
2,01-12/DrDoS_MSSQL.csv,4524498,88,14,0,1801.66
3,01-12/DrDoS_NetBIOS.csv,4094986,88,8,0,1618.84
4,01-12/DrDoS_NTP.csv,1217007,88,31,0,615.13
5,01-12/DrDoS_SNMP.csv,5161377,88,12,0,2071.93
6,01-12/DrDoS_SSDP.csv,2611374,88,2,0,1194.65
7,01-12/DrDoS_UDP.csv,3136802,88,8,0,1436.27
8,01-12/Syn.csv,1582681,88,202277,0,607.79
9,01-12/TFTP.csv,20107827,88,10497,0,8871.09
10,01-12/UDPLag.csv,370605,88,36132,0,150.65
11,03-11/LDAP.csv,2113234,88,13,0,831.03
12,03-11/MSSQL.csv,5775786,88,7,0,2275.68
13,03-11/NetBIOS.csv,3455899,88,6,0,1352.76
14,03-11/Portmap.csv,191694,88,1,0,74.97
15,03-11/Syn.csv,4320541,88,94,482799,1790.40
16,03-11/UDP.csv,3782206,88,4,0,1709.74
17,03-11/UDPLag.csv,725165,88,3,0,304.98

In [4]:
label_counts = {}

for file in csv_files:
    print(f"Reading labels from {file.parent.name}/{file.name}...")
    labels = pd.read_csv(file, usecols=lambda c: c.strip() == "Label")
    label_counts[f"{file.parent.name}/{file.name}"] = labels.iloc[:, 0].value_counts().to_dict()

Reading labels from 01-12/DrDoS_DNS.csv...

Reading labels from 01-12/DrDoS_LDAP.csv...

Reading labels from 01-12/DrDoS_MSSQL.csv...

Reading labels from 01-12/DrDoS_NetBIOS.csv...

Reading labels from 01-12/DrDoS_NTP.csv...

Reading labels from 01-12/DrDoS_SNMP.csv...

Reading labels from 01-12/DrDoS_SSDP.csv...

Reading labels from 01-12/DrDoS_UDP.csv...

Reading labels from 01-12/Syn.csv...

Reading labels from 01-12/TFTP.csv...

Reading labels from 01-12/UDPLag.csv...

Reading labels from 03-11/LDAP.csv...

Reading labels from 03-11/MSSQL.csv...

Reading labels from 03-11/NetBIOS.csv...

Reading labels from 03-11/Portmap.csv...

Reading labels from 03-11/Syn.csv...

Reading labels from 03-11/UDP.csv...

Reading labels from 03-11/UDPLag.csv...

In [5]:
label_summary = pd.DataFrame(label_counts).fillna(0).astype(int)
label_summary

,01-12/DrDoS_DNS.csv,01-12/DrDoS_LDAP.csv,01-12/DrDoS_MSSQL.csv,01-12/DrDoS_NetBIOS.csv,01-12/DrDoS_NTP.csv,01-12/DrDoS_SNMP.csv,01-12/DrDoS_SSDP.csv,01-12/DrDoS_UDP.csv,01-12/Syn.csv,01-12/TFTP.csv,01-12/UDPLag.csv,03-11/LDAP.csv,03-11/MSSQL.csv,03-11/NetBIOS.csv,03-11/Portmap.csv,03-11/Syn.csv,03-11/UDP.csv,03-11/UDPLag.csv
DrDoS_DNS,5071011,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
BENIGN,3402,1612,2006,1707,14365,1507,763,2157,392,25247,3705,5124,2794,1321,4734,35790,3134,4068
DrDoS_LDAP,0,2179930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_MSSQL,0,0,4522492,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_NetBIOS,0,0,0,4093279,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_NTP,0,0,0,0,1202642,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_SNMP,0,0,0,0,0,5159870,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_SSDP,0,0,0,0,0,0,2610611,0,0,0,0,0,0,0,0,0,0,0
DrDoS_UDP,0,0,0,0,0,0,0,3134645,0,0,0,0,0,0,0,0,0,0
Syn,0,0,0,0,0,0,0,0,1582289,0,0,0,0,0,0,4284751,0,606749
TFTP,0,0,0,0,0,0,0,0,0,20082580,0,0,0,0,0,0,0,0
UDP-lag,0,0,0,0,0,0,0,0,0,0,366461,0,0,0,0,0,0,0
WebDDoS,0,0,0,0,0,0,0,0,0,0,439,0,0,0,0,0,0,0
LDAP,0,0,0,0,0,0,0,0,0,0,0,1905191,9931,0,0,0,0,0
NetBIOS,0,0,0,0,0,0,0,0,0,0,0,202919,0,3454578,0,0,0,0
MSSQL,0,0,0,0,0,0,0,0,0,0,0,0,5763061,0,0,0,24392,0
Portmap,0,0,0,0,0,0,0,0,0,0,0,0,0,0,186960,0,0,0
UDP,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3754680,112475
UDPLag,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1873

In [6]:
label_summary.to_csv("../reports/label_distribution.csv")
label_summary

,01-12/DrDoS_DNS.csv,01-12/DrDoS_LDAP.csv,01-12/DrDoS_MSSQL.csv,01-12/DrDoS_NetBIOS.csv,01-12/DrDoS_NTP.csv,01-12/DrDoS_SNMP.csv,01-12/DrDoS_SSDP.csv,01-12/DrDoS_UDP.csv,01-12/Syn.csv,01-12/TFTP.csv,01-12/UDPLag.csv,03-11/LDAP.csv,03-11/MSSQL.csv,03-11/NetBIOS.csv,03-11/Portmap.csv,03-11/Syn.csv,03-11/UDP.csv,03-11/UDPLag.csv
DrDoS_DNS,5071011,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
BENIGN,3402,1612,2006,1707,14365,1507,763,2157,392,25247,3705,5124,2794,1321,4734,35790,3134,4068
DrDoS_LDAP,0,2179930,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_MSSQL,0,0,4522492,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_NetBIOS,0,0,0,4093279,0,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_NTP,0,0,0,0,1202642,0,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_SNMP,0,0,0,0,0,5159870,0,0,0,0,0,0,0,0,0,0,0,0
DrDoS_SSDP,0,0,0,0,0,0,2610611,0,0,0,0,0,0,0,0,0,0,0
DrDoS_UDP,0,0,0,0,0,0,0,3134645,0,0,0,0,0,0,0,0,0,0
Syn,0,0,0,0,0,0,0,0,1582289,0,0,0,0,0,0,4284751,0,606749
TFTP,0,0,0,0,0,0,0,0,0,20082580,0,0,0,0,0,0,0,0
UDP-lag,0,0,0,0,0,0,0,0,0,0,366461,0,0,0,0,0,0,0
WebDDoS,0,0,0,0,0,0,0,0,0,0,439,0,0,0,0,0,0,0
LDAP,0,0,0,0,0,0,0,0,0,0,0,1905191,9931,0,0,0,0,0
NetBIOS,0,0,0,0,0,0,0,0,0,0,0,202919,0,3454578,0,0,0,0
MSSQL,0,0,0,0,0,0,0,0,0,0,0,0,5763061,0,0,0,24392,0
Portmap,0,0,0,0,0,0,0,0,0,0,0,0,0,0,186960,0,0,0
UDP,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3754680,112475
UDPLag,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1873